I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 65, in script
    "You feel like turning back, but you knew that this is the moment you've been waiting for."
IOError: Couldn't find file 'kochira'.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 65, in script
    "You feel like turning back, but you knew that this is the moment you've been waiting for."
  File "renpy/ast.py", line 921, in execute
    renpy.exports.say(who, what, *args, **kwargs)
  File "renpy/exports.py", line 1373, in say
    who(what, *args, **kwargs)
  File "renpy/character.py", line 1266, in __call__
    self.do_display(who, what, cb_args=self.cb_args, dtt=dtt, **display_args)
  File "renpy/character.py", line 930, in do_display
    **display_args)
  File "renpy/character.py", line 666, in display_say
    rv = renpy.ui.interact(mouse='say', type=type, roll_forward=roll_forward)
  File "renpy/ui.py", line 299, in interact
    rv = renpy.game.interface.interact(roll_forward=roll_forward, **kwargs)
  File "renpy/display/core.py", line 3377, in interact
    repeat, rv = self.interact_core(preloads=preloads, trans_pause=trans_pause, pause=pause, pause_start=pause_start, **kwargs) # type: ignore
  File "renpy/display/core.py", line 4097, in interact_core
    renpy.audio.audio.periodic()
  File "renpy/audio/audio.py", line 1166, in periodic
    raise_(exc[0], exc[1], exc[2])
  File "renpy/audio/audio.py", line 1144, in periodic_thread_main
    periodic_pass()
  File "renpy/audio/audio.py", line 1086, in periodic_pass
    c.periodic()
  File "renpy/audio/audio.py", line 517, in periodic
    topf = load(filename)
  File "renpy/audio/audio.py", line 70, in load
    rv = renpy.loader.load(fn)
  File "renpy/loader.py", line 820, in load
    raise IOError("Couldn't find file '%s'." % name)
IOError: Couldn't find file 'kochira'.

Windows-10-10.0.19041 AMD64
Ren'Py 7.5.1.22070801
The Cheems 1.0
Tue May 16 18:51:41 2023
